# Sumario {.unnumbered}

## **Unidad 1: Sospechosos habituales**

Marx, Nietzsche y Freud, nuestros célebres “pensadores de la sospecha”, constituyen pilares básicos de todo pensamiento. Deconstruir al Marx hegeliano y al materialista dialéctico, reconstruir al Freud menos psicoanalítico y destruir al Nietzsche más hipocondríaco es la tarea planteada para esta (des)unidad temática, fiesta de los sentidos en la que Simone Weil oficiará de maestra de ceremonias.

En esta primera unidad, se aborda la influencia y la tarea crítica de Marx, Nietzsche y Freud, conocidos como "pensadores de la sospecha". La autora propone desentrañar, reconstruir y...

## **Unidad 2: ¡Danzad, danzad, malditos!**

Foucault y Deleuze anudados a sus cuerpos sin órganos, Lacan y Lévi-Strauss llenos de casillas vacías, Bataille y Blanchot confrontando sus partes malditas, Barthes y Debord enganchados al espectáculo, Baudrillard y Bourdieu desplegando sus *habitus*: pocos escenarios como el que se mueve alrededor del estructuralismo francés nos permiten hallar tan fascinantes parejas de baile. “Pase sin llamar”, se lee en el cartel colgado en la puerta... ¿entramos?

En esta segunda unidad, se adentra en el intrigante mundo del estructuralismo francés, presentando a Foucault, Deleuze, Lacan, Lévi-Strauss, Bataille, Blanchot, Barthes, Debord, Baudrillard y Bourdieu como figuras en un sugerente baile intelectual.

## **Unidad 3: *Flâneurs* de ciudades invisibles**

Ciudad es el nombre que se da a una enfermedad nerviosa muy grave: Benjamin, Baudelaire, Simmel y Mumford toman las constantes vitales a la ciudad de ayer, hoy y siempre, encontrándose para hacer botánica en el asfalto con curtidos urbanitas como Kafka y Poe, Queneau y Perec, Borges y Calvino. ¿A qué (pre)textos podremos recurrir para acercarnos a ellos sin sentirnos incomprendidos ni rechazados?

En esta tercera unidad, se explora la relación entre ciudad y literatura, destacando a Benjamin, Baudelaire, Simmel y Mumford como "flâneurs" urbanos. Se plantea la búsqueda de textos que faciliten la aproximación a estas figuras sin incomodidades.

## **Unidad 4: En la salud y en la enfermedad**

Casas muertas y habitaciones propias, metáforas de dolencias y sacrificios imaginarios, cruda realidad y realidad pura y dura: la salud y la enfermedad del cuerpo y del alma son magistralmente abordadas por Dostoievski y Woolf, Sontag y Le Guin, London y Perkins Gilman, en una serie de maravillosos textos encargados de abrir las puertas a la vida y a la libertad (cuando son lo mismo).

La última unidad se sumerge en la dualidad de la salud y la enfermedad, explorando las representaciones literarias de Dostoievski, Woolf, Sontag, Le Guin, London y Perkins Gilman. Se destaca la capacidad de estos textos para abrir las puertas a la vida y la libertad.
